language: python
python:
  - "3.3"
  - "3.5"
  - "3.6"
before_install:
  - pip install matplotlib
  - pip install numpy
  - pip install scipy
install:
  - python setup.py -q install
script:
  - StoatyDive.py -h



